1. **Profitability** — Which product categories generate the most profit, and how much of that comes from sales volume versus per-unit margin?

2. **Returns & discounting** — Does heavier discounting correlate with higher return rates, and how much profit (if any) do returns actually cost each category?

In [51]:
import pandas as pd

In [52]:
categories = pd.read_csv("../retail_data/categories.csv")
customers = pd.read_csv("../retail_data/customers.csv")
orders = pd.read_csv("../retail_data/orders.csv")
order_details = pd.read_csv("../retail_data/order_details.csv")
products = pd.read_csv("../retail_data/products.csv")

In [53]:
categories.info()
categories.head()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CategoryID    10 non-null     str
 1   CategoryName  10 non-null     str
dtypes: str(2)
memory usage: 292.0 bytes

  CategoryID    CategoryName
0  CTGRY0001  Meat & Poultry
1  CTGRY0002    Dairy & Eggs
2  CTGRY0003         Produce
3  CTGRY0004       Beverages
4  CTGRY0005          Bakery

In [54]:
customers.info()
customers.head()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       1000 non-null   str
 1   Gender           1000 non-null   str
 2   Age              1000 non-null   int64
 3   City             1000 non-null   str
 4   Region           1000 non-null   str
 5   CustomerSegment  1000 non-null   str
 6   SignUpDate       1000 non-null   str
dtypes: int64(1), str(6)
memory usage: 54.8 KB

  CustomerID  Gender  Age      City   Region CustomerSegment  SignUpDate
0  CSTMR0001    Male   29  Istanbul  Marmara        Standard  2020-04-13
1  CSTMR0002   Other   40  Istanbul  Marmara        Standard  2020-04-08
2  CSTMR0003  Female   36     Bursa  Marmara         Premium  2022-08-14
3  CSTMR0004    Male   18  Istanbul  Marmara         Premium  2022-03-26
4  CSTMR0005    Male   43     Izmir   Aegean         Premium  2021-04-04

In [55]:
orders.info()
orders.head()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     10000 non-null  str
 1   CustomerID  10000 non-null  str
 2   OrderDate   10000 non-null  str
 3   OrderTime   10000 non-null  str
dtypes: str(4)
memory usage: 312.6 KB

    OrderID CustomerID   OrderDate OrderTime
0  ORD00001  CSTMR0983  2021-04-10  12:53:24
1  ORD00002  CSTMR0703  2024-04-21  22:08:16
2  ORD00003  CSTMR0920  2022-10-27  10:21:26
3  ORD00004  CSTMR0158  2025-11-07  22:24:27
4  ORD00005  CSTMR0834  2021-09-05  13:23:16

In [63]:
order_details.info()
order_details.head()

<class 'pandas.DataFrame'>
RangeIndex: 30271 entries, 0 to 30270
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       30271 non-null  str
 1   ProductID     30271 non-null  str
 2   Quantity      30271 non-null  int64
 3   UnitCost      30271 non-null  float64
 4   UnitPrice     30271 non-null  float64
 5   DiscountRate  30271 non-null  float64
 6   IsReturned    30271 non-null  int64
 7   ReturnDate    30271 non-null  str
 8   ReturnTime    30271 non-null  str
 9   ReturnReason  1424 non-null   str
dtypes: float64(3), int64(2), str(5)
memory usage: 2.3 MB

,OrderID,ProductID,Quantity,UnitCost,UnitPrice,DiscountRate,IsReturned,ReturnDate,ReturnTime,ReturnReason
0,ORD00001,PRDCT0056,3,2.14,3.38,0.00,0,9999-12-31,00:00:00,NaN
1,ORD00002,PRDCT0028,2,4.17,5.31,0.00,0,9999-12-31,00:00:00,NaN
2,ORD00002,PRDCT0001,13,20.36,25.77,0.05,0,9999-12-31,00:00:00,NaN
3,ORD00003,PRDCT0030,2,0.90,1.35,0.00,0,9999-12-31,00:00:00,NaN
4,ORD00004,PRDCT0003,3,12.84,20.35,0.00,0,9999-12-31,00:00:00,NaN

In [57]:
products.info()
products.head()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    100 non-null    str
 1   ProductName  100 non-null    str
 2   CategoryID   100 non-null    str
dtypes: str(3)
memory usage: 2.5 KB

   ProductID            ProductName CategoryID
0  PRDCT0001      ABC's Beef Ribeye  CTGRY0001
1  PRDCT0002   XYZ's Chicken Breast  CTGRY0001
2  PRDCT0003    KLM's Turkey Breast  CTGRY0001
3  PRDCT0004       ABC's Lamb Chops  CTGRY0001
4  PRDCT0005  XYZ's Atlantic Salmon  CTGRY0001

In [58]:
categories.isnull().sum()
categories.head()

  CategoryID    CategoryName
0  CTGRY0001  Meat & Poultry
1  CTGRY0002    Dairy & Eggs
2  CTGRY0003         Produce
3  CTGRY0004       Beverages
4  CTGRY0005          Bakery

In [ ]:
## Answering common questions
##Total revenue?
total_revenue = order_details['UnitPrice'].sum()
print("Total Revenue: " + str(total_revenue.round(2)))

##Total profit?
total_profit = order_details['UnitPrice'].sum() - order_details['UnitCost'].sum()
print("Total Profit: " + str(total_profit.round(2)))

##Total number of orders?
total_orders = orders['OrderID'].nunique()
print("Total Orders: " + str(total_orders))

##Number of products sold?
total_products_sold = order_details['ProductID'].nunique()
print("Total Products Sold: " + str(total_products_sold))

Total Revenue: 296471.84
Total Profit: 90527.24
Total Orders: 10000
Total Products Sold: 100
Average Order Value: 9.79
Average Profit Per Order: 2.99
Profit Margin: 30.53

In [ ]:
##Product and category questions
##Product with the most revenue?
product_w_most_revenue = order_details.groupby('ProductID')['UnitPrice'].sum().idxmax()
print("Product with Most Revenue: " + str(product_w_most_revenue))

##Product with most profit?
product_w_most_profit = order_details.groupby('ProductID').apply(lambda x: (x['UnitPrice'] - x['UnitCost']).sum()).idxmax()
print("Product with Most Profit: " + str(product_w_most_profit))

##Are the highest selling products the most profitable?
highest_selling = order_details.groupby('ProductID')['Quantity'].sum().idxmax()
is_most_profitable = product_w_most_profit == highest_selling
print("Is the highest selling product also the most profitable? " + str(is_most_profitable))

Product with Most Revenue: PRDCT0007
Product with Most Profit: PRDCT0007
Is the highest selling product also the most profitable? False